[package]
name = "warblersneeds"
version = "0.1.0"
edition = "2021"
readme = "README.md"
license = "MIT OR Apache-2.0"
exclude = ["assets/", "scripts/"]
keywords = ["bevy", "gamedev", "graphics", "grass", "rendering"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["serialize", "debug"]
serialize = ["dep:serde", "dep:ron"]
debug = ["dep:bevy-inspector-egui"]

[dependencies]
bytemuck = "1.13.0"
rand = {version = "0.8.5", features = ["small_rng"]}
bevy = {version = "0.9.1"}

# needed for serialize feature
serde = {version = "1.0.152", optional = true}
ron = {version = "0.8", optional = true}

bevy-inspector-egui = {version = "0.17.0", optional = true}


[[example]]
name = "load_from_plane"
path = "examples/load_from_plane.rs"
[[example]]
name = "grass_colors"
path = "examples/grass_colors.rs"
