[package]
name = "warbler_grass"
version = "0.1.0"
edition = "2021"
readme = "README.md"
license = "MIT OR Apache-2.0"
exclude = ["scripts/"]
keywords = ["bevy", "gamedev", "graphics", "grass", "rendering"]
repository = "https://github.com/EmiOnGit/warbler_grass"
description = "A bevy plugin for creating 3d grass in your game"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["serialize", "debug"]
serialize = ["dep:serde", "dep:ron"]
debug = ["dep:bevy-inspector-egui"]

[dependencies]
bytemuck = "1.13.0"
rand = {version = "0.8.5", features = ["small_rng"]}
bevy = {version = "0.9.1"}
bevy_mod_raycast = "*"
bitflags = "1.3.2"
# needed for serialize feature
serde = {version = "1.0.152", optional = true}
ron = {version = "0.8", optional = true}

bevy-inspector-egui = {version = "0.17.0", optional = true}



[[example]]
name = "load_custom"
path = "examples/load_custom.rs"

[[example]]
name = "load_height_map"
path = "examples/load_height_map.rs"

[[example]]
name = "load_many_chunks"
path = "examples/load_many_chunks.rs"

[[example]]
name = "grass_colors"
path = "examples/grass_colors.rs"

[[example]]
name = "stress_test"
path = "examples/stress_test.rs"

[[example]]
name = "swap_grass_mesh"
path = "examples/swap_grass_mesh.rs"
