[package]
name = "warbler_grass"
version = "0.2.0"
edition = "2021"
readme = "README.md"
license = "MIT OR Apache-2.0"
exclude = ["scripts/"]
keywords = ["bevy", "gamedev", "graphics", "grass", "rendering"]
repository = "https://github.com/EmiOnGit/warbler_grass"
description = "A bevy plugin for creating 3d grass in your game"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
bytemuck = "1.13.0"
rand = {version = "0.8.5", features = ["small_rng"]}
bevy = {version = "0.10.0"}
bitflags = "1.3.2"
serde = "1.0.153"

[[example]]
name = "load_explicit"
path = "examples/load_explicit.rs"

[[example]]
name = "load_grass"
path = "examples/load_grass.rs"

[[example]]
name = "many_chunks"
path = "examples/many_chunks.rs"

[[example]]
name = "grass_colors"
path = "examples/grass_colors.rs"

[[example]]
name = "stress_test"
path = "examples/stress_test.rs"

[[example]]
name = "grass_mesh"
path = "examples/grass_mesh.rs"
